## Stage F8 / F9 — Cat 3 (buildDoc + docEmit) property tests.
##
## - **P4: doc structural round-trip.** For parseable B,
##   parse(B) → emitDoc → parse → docEqual.
##
## - **P5: preserve byte-exact** (lands in F9).
##
## P6 (preserve-under-mutation) is intentionally deferred until
## the mutation algebra is designed — splice machinery was removed,
## and a fresh state-machine over (set-name, set-prop, add-arg,
## append-child, ...) needs an RFC. The existing 243/243 preserve
## corpus carries most of P6's coverage in the meantime.
##
## Gated by NKDL_PROPTEST=1.

import std/unittest

import proptest

import ../src/api
import ../src/ast
import ../src/doc_emit
import ../src/emitter
import ../src/kdl_block
import ../src/parser
import ../src/pragmas

kdl:
  type Service {.kdlNode: "service".} = object
    name {.kdlArg.}: string
    port {.kdlProp.}: int

  type Item {.kdlNode: "item".} = object
    label {.kdlArg.}: string

  type Catalog {.kdlNode: "catalog".} = object
    name {.kdlArg.}: string
    items {.kdlChild.}: seq[Item]

proc docRoundtrip(src: string): KdlDoc =
  let r = parse(src)
  doAssert r.isOk
  var e = newBufferEmitter()
  emitDoc(r.get, e)
  let r2 = parse(e.finish())
  doAssert r2.isOk
  r2.get

suite "P4 — Cat 3 doc structural round-trip":

  test "fixed Service input round-trips structurally (tracer)":
    let src = "service \"web\" port=80"
    let r = parse(src)
    check r.isOk
    let doc1 = r.get
    let doc2 = docRoundtrip(src)
    check docEqual(doc1, doc2)

  property "any parseable Service-shaped B round-trips structurally":
    with Settings(maxExamples: 200, testId: "p4-service")
    given name in strings(1, 32), port in integers(0, 65535)
    let v = Service(name: name, port: port)
    let src = encode(v)
    let r = parse(src)
    ensure r.isOk
    let doc1 = r.get
    let doc2 = docRoundtrip(src)
    ensure docEqual(doc1, doc2)

suite "P5 — preserve byte-exact":

  test "fixed Service input preserves byte-exact (tracer)":
    let src = "service \"web\" port=80"
    let r = parse(src, preserveFormat = true)
    check r.isOk
    var e = newBufferEmitter()
    emitDocPreserve(r.get, e)
    check e.finish() == src

  property "encoded T preserves byte-exact when reparsed in preserve mode":
    # The bytes generated by encode[T] are canonical-form output.
    # parse(.., preserveFormat=true) + emitDocPreserve must
    # round-trip them byte-for-byte — preserve mode's claim is
    # exactly 'whatever you parsed, you get back.'
    with Settings(maxExamples: 200, testId: "p5-service")
    given name in strings(1, 32), port in integers(0, 65535)
    let src = encode(Service(name: name, port: port))
    let r = parse(src, preserveFormat = true)
    ensure r.isOk
    var e = newBufferEmitter()
    emitDocPreserve(r.get, e)
    ensure e.finish() == src

suite "P4 — Cat 3 doc structural round-trip (continued)":

  property "any parseable Catalog-shaped B round-trips structurally":
    with Settings(maxExamples: 150, testId: "p4-catalog")
    given catName in strings(1, 24),
          itemNames in lists(strings(1, 16), 0, 8)
    var items: seq[Item] = @[]
    for ln in itemNames: items.add(Item(label: ln))
    let v = Catalog(name: catName, items: items)
    let src = encode(v)
    let r = parse(src)
    ensure r.isOk
    let doc1 = r.get
    let doc2 = docRoundtrip(src)
    ensure docEqual(doc1, doc2)
