## Visitor-based typed parser. The first part of the typed-direct path
## architecture from issue #1.
##
## ## Design (per "E′" recommendation, see issue #1 discussion)
##
## One grammar, many visitors. The parser walks the token stream and
## dispatches into the visitor's methods. Two visitors live in tree:
##   - `DocBuilder` (in parser.nim) builds the existing `KdlDoc`
##   - `TypedBuilder[T]` (generated by `deriveDecode`) writes directly
##     into a typed T value
##
## Visitors are duck-typed: any object with the required methods
## satisfies the protocol. The compiler monomorphizes per-visitor so
## the dispatch is static and inline-able.
##
## ## Visitor protocol
##
## A type `V` is a parse visitor if it implements:
##
##   proc visitBeginNode(v: var V,
##                       nameStr: openArray[char],
##                       nodeSpan: Span): Result[void, ParseError]
##   proc visitArg(v: var V, idx: int, tok: Token,
##                 stream: TokenStream): Result[void, ParseError]
##   proc visitProp(v: var V, keyStr: openArray[char],
##                  tok: Token, stream: TokenStream): Result[void, ParseError]
##   proc visitBeginChildren(v: var V): Result[void, ParseError]
##   proc visitEndChildren(v: var V): Result[void, ParseError]
##   proc visitEndNode(v: var V): Result[void, ParseError]
##
## `nodeSpan` is the span of the node-name token (used for error
## reporting). All methods return Result so errors propagate without
## raising (preserves `embed[T]` compile-time-eval semantics).

import ./[lexer, intern, spans]

func openArrayToString*(s: openArray[char]): string {.noSideEffect.} =
  ## VM-friendly conversion. `cast[string](@seq[char])` blows up in
  ## NimVM ("does not support 'cast' from tySequence to tyString"); a
  ## newString + byte-copy works both at runtime and at compile time.
  ## Used by the macro-emitted visitProp case dispatch.
  result = newString(s.len)
  for i in 0 ..< s.len: result[i] = s[i]

proc parseInto*[T](source: string, sourcePath = "<input>"):
    Result[T, ParseError] =
  ## Typed entry point. Used as `parseInto[Rule]("...")` or
  ## `parseInto[seq[Rule]]("...")`. Resolves the per-type visitor via
  ## `deriveVisitor[T]`-emitted `kdlBuildVisitor` / `kdlBuildVisitorSeq`
  ## overload at instantiation time.
  mixin kdlBuildVisitor, kdlBuildVisitorSeq
  when T is seq:
    type Elem = typeof(default(T)[0])
    kdlBuildVisitorSeq(Elem, source, sourcePath)
  else:
    kdlBuildVisitor(T, source, sourcePath)

proc parseDocumentWith*[V](source: string, visitor: var V,
                           sourcePath = "<input>"):
    Result[void, ParseError] =
  ## Walks every top-level node in `source` through `visitor`.
  ## Each node fires visitBeginNode/...visitEndNode independently. The visitor
  ## is responsible for accumulating results across nodes (the seq[T]
  ## entry point's emitted visitor does this).
  var interner = initInterner()
  let stream = lex(source, interner)
  for t in stream.tokens:
    if t.kind == tkError:
      return err[void, ParseError](stream.errorPayloads[t.errIdx])

  var cursor = 0
  template peek(off = 0): Token =
    if cursor + off < stream.tokens.len: stream.tokens[cursor + off]
    else: Token(kind: tkEof, span: pointSpan(StartPosition))

  # Skip an optional `(IDENT)` type annotation. KDL v2 allows them
  # before node names AND before any value (arg or prop). The typed-
  # direct path doesn't currently route annotations to the visitor —
  # they're accepted and ignored.
  template skipTypeAnno() =
    if peek().kind == tkLParen:
      inc cursor
      if peek().kind notin {tkIdent, tkString, tkRawString}:
        return err[void, ParseError](initError(peParseExpected, peek().span,
          "expected identifier or string inside type annotation"))
      inc cursor
      if peek().kind != tkRParen:
        return err[void, ParseError](initError(peParseExpected, peek().span,
          "expected ')' to close type annotation"))
      inc cursor

  while true:
    while peek().kind == tkNewline: inc cursor
    if peek().kind == tkEof: break

    skipTypeAnno()       # optional (type) before node name
    let nameTok = peek()
    if nameTok.kind != tkIdent:
      return err[void, ParseError](initError(peParseExpected, nameTok.span,
        "expected node name"))
    inc cursor

    let nameStr = interner.lookup(nameTok.ident)
    let bRes = visitor.visitBeginNode(nameStr.toOpenArray(0, nameStr.high),
                                  nameTok.span)
    if bRes.isErr: return bRes

    var argIdx = 0
    var done = false
    while not done:
      # A `(type)` annotation can prefix an arg value. (Prop keys
      # can't be annotated; the annotation modifies a value.)
      if peek().kind == tkLParen: skipTypeAnno()
      let t = peek()
      case t.kind
      of tkNewline, tkSemicolon, tkEof, tkRBrace:
        break
      of tkLBrace:
        # children block. Bracket the inner-node walk with
        # visitBeginChildren / visitEndChildren. Each inner node fires
        # the same begin/arg/prop/end protocol on the SAME parent
        # visitor; the visitor's macro-emitted dispatch routes to the
        # right child-field builder based on its inChildren state.
        inc cursor   # consume `{`
        let bcRes = visitor.visitBeginChildren()
        if bcRes.isErr: return bcRes
        while true:
          while peek().kind == tkNewline: inc cursor
          if peek().kind == tkRBrace: break
          if peek().kind == tkEof:
            return err[void, ParseError](initError(peParseExpected, peek().span,
              "expected `}` to close children block"))
          # recursive walk of one child node
          skipTypeAnno()    # optional (type) before child node name
          let childTok = peek()
          if childTok.kind != tkIdent:
            return err[void, ParseError](initError(peParseExpected, childTok.span,
              "expected child node name"))
          inc cursor
          let childName = interner.lookup(childTok.ident)
          let cbRes = visitor.visitBeginNode(childName.toOpenArray(0, childName.high),
                                             childTok.span)
          if cbRes.isErr: return cbRes
          var cArgIdx = 0
          while true:
            let ct = peek()
            case ct.kind
            of tkNewline, tkSemicolon, tkEof, tkRBrace:
              break
            of tkIdent, tkString, tkRawString:
              if peek(1).kind == tkEquals:
                let cKeyTok = peek()
                let cKeyHandle =
                  case cKeyTok.kind
                  of tkIdent: cKeyTok.ident
                  of tkString: interner.intern(stream.stringPayloads[cKeyTok.strIdx])
                  of tkRawString: interner.intern(stream.rawStringPayloads[cKeyTok.rawIdx])
                  else: InvalidInterned
                cursor += 2
                skipTypeAnno()     # optional (type) before prop value
                let cValTok = peek()
                inc cursor
                let cKeyStr = interner.lookup(cKeyHandle)
                let cpRes = visitor.visitProp(cKeyStr.toOpenArray(0, cKeyStr.high),
                                              cValTok, stream)
                if cpRes.isErr: return cpRes
              else:
                inc cursor
                let caRes = visitor.visitArg(cArgIdx, ct, stream)
                if caRes.isErr: return caRes
                inc cArgIdx
            of tkNumber, tkKeyword:
              inc cursor
              let caRes = visitor.visitArg(cArgIdx, ct, stream)
              if caRes.isErr: return caRes
              inc cArgIdx
            else:
              return err[void, ParseError](initError(peParseUnexpected, ct.span,
                "unexpected token in child node entries"))
          let ceRes = visitor.visitEndNode()
          if ceRes.isErr: return ceRes
        inc cursor  # consume `}`
        let ecRes = visitor.visitEndChildren()
        if ecRes.isErr: return ecRes
        done = true
      of tkIdent, tkString, tkRawString:
        if peek(1).kind == tkEquals:
          let keyTok = peek()
          let keyHandle =
            case keyTok.kind
            of tkIdent: keyTok.ident
            of tkString: interner.intern(stream.stringPayloads[keyTok.strIdx])
            of tkRawString: interner.intern(stream.rawStringPayloads[keyTok.rawIdx])
            else: InvalidInterned
          cursor += 2
          skipTypeAnno()       # optional (type) before prop value
          let valueTok = peek()
          inc cursor
          let keyStr = interner.lookup(keyHandle)
          let pRes = visitor.visitProp(keyStr.toOpenArray(0, keyStr.high),
                                   valueTok, stream)
          if pRes.isErr: return pRes
        else:
          inc cursor
          let aRes = visitor.visitArg(argIdx, t, stream)
          if aRes.isErr: return aRes
          inc argIdx
      of tkNumber, tkKeyword:
        inc cursor
        let aRes = visitor.visitArg(argIdx, t, stream)
        if aRes.isErr: return aRes
        inc argIdx
      else:
        return err[void, ParseError](initError(peParseUnexpected, t.span,
          "unexpected token in node entries"))

    let eRes = visitor.visitEndNode()
    if eRes.isErr: return eRes

  ok(void, ParseError)

proc parseWith*[V](source: string, visitor: var V,
                   sourcePath = "<input>"): Result[void, ParseError]
    {.noSideEffect.} =
  ## Single-node convenience. Delegates to parseDocumentWith so the
  ## LBrace/children/recovery logic lives in one place. The visitor
  ## sees the same begin/arg/prop/end protocol either way.
  parseDocumentWith(source, visitor, sourcePath)
