## Visitor-based typed parser. The first part of the typed-direct path
## architecture from issue #1.
##
## ## Design (per "E′" recommendation, see issue #1 discussion)
##
## One grammar, many visitors. The parser walks the token stream and
## dispatches into the visitor's methods. Visitors that live in tree:
##   - `DocBuilder` (src/doc_builder.nim) builds the existing `KdlDoc`
##   - `TypedBuilder[T]` (generated by `deriveVisitor`) writes directly
##     into a typed T value
##
## Visitors are duck-typed: any object with the required methods
## satisfies the protocol. The compiler monomorphizes per-visitor so
## the dispatch is static and inline-able.
##
## ## Capability-driven specialization
##
## Each visitor declares a `visitorCaps` template returning a compile-
## time `set[VisitorCap]`. parseDocumentWith branches on `when X in
## visitorCaps(V):` so visitors that don't need a feature don't pay for
## the routing code. Zero abstraction tax: TypedBuilder's hot path
## stays identical to before this refactor.
##
## ## Visitor protocol (core methods, required for all visitors)
##
##   proc visitBeginNode(v: var V, nameStr: openArray[char], nodeSpan: Span):
##       Result[void, ParseError]
##   proc visitArg(v: var V, idx: int, tok: Token, stream: TokenStream):
##       Result[void, ParseError]
##   proc visitProp(v: var V, keyStr: openArray[char],
##                  tok: Token, stream: TokenStream):
##       Result[void, ParseError]
##   proc visitBeginChildren(v: var V): Result[void, ParseError]
##   proc visitEndChildren(v: var V): Result[void, ParseError]
##   proc visitEndNode(v: var V): Result[void, ParseError]
##
## Optional methods (only required if the corresponding cap is declared):
##   visitNodeTypeAnno, visitValueTypeAnno   (vcNodeAnno / vcValueAnno)
##   visitSlashdash                          (vcSlashdash)
##
## All methods return `Result[void, ParseError]` so errors propagate
## without raising (preserves `embed[T]` compile-time-eval semantics).

import ./[lexer, intern, spans]

type
  VisitorCap* = enum
    ## Capabilities a visitor opts into. parseDocumentWith gates routing
    ## code per cap so unused features cost nothing.
    vcArgs            ## visitArg events for positional values
    vcProps           ## visitProp events for `key=value`
    vcChildren        ## visitBeginChildren / visitEndChildren + recursion
    vcNodeAnno        ## visitNodeTypeAnno before visitBeginNode
    vcValueAnno       ## visitValueTypeAnno before visitArg / visitProp
    vcSlashdash       ## visitSlashdash before slashdash'd thing

func openArrayToString*(s: openArray[char]): string {.noSideEffect.} =
  ## VM-friendly conversion. `cast[string](@seq[char])` blows up in
  ## NimVM ("does not support 'cast' from tySequence to tyString"); a
  ## newString + byte-copy works both at runtime and at compile time.
  ## Used in error messages only — the hot-path dispatch uses bytesEq.
  result = newString(s.len)
  for i in 0 ..< s.len: result[i] = s[i]

func bytesEq*(s: openArray[char], lit: static string): bool
    {.inline, noSideEffect.} =
  ## Zero-alloc byte compare against a compile-time-known string.
  if s.len != lit.len: return false
  for i in 0 ..< lit.len:
    if s[i] != lit[i]: return false
  true

proc parseInto*[T](source: string, sourcePath = "<input>"):
    Result[T, ParseError] =
  ## Typed entry point. Resolves the per-type visitor via
  ## `deriveVisitor`-emitted `kdlBuildVisitor` / `kdlBuildVisitorSeq`
  ## overload at instantiation time.
  mixin kdlBuildVisitor, kdlBuildVisitorSeq
  when T is seq:
    type Elem = typeof(default(T)[0])
    kdlBuildVisitorSeq(Elem, source, sourcePath)
  else:
    kdlBuildVisitor(T, source, sourcePath)

# ---------------------------------------------------------------------------
# parseDocumentWith — visitor-parameterized parser
# ---------------------------------------------------------------------------

proc parseNodeWith[V](source: string, visitor: var V,
                      stream: TokenStream, cursor: var int):
    Result[void, ParseError]

proc parseDocumentWith*[V](source: string, visitor: var V,
                           sourcePath = "<input>"):
    Result[void, ParseError] =
  ## Walks every top-level node in `source` through `visitor`.
  mixin visitorCaps
  var interner = initInterner()
  interner.disabled = true   # visitors read bytes from source directly
  let stream = lex(source, interner)
  for t in stream.tokens:
    if t.kind == tkError:
      return err[void, ParseError](stream.errorPayloads[t.errIdx])

  var cursor = 0
  template peek(off = 0): Token =
    if cursor + off < stream.tokens.len: stream.tokens[cursor + off]
    else: Token(kind: tkEof, span: pointSpan(StartPosition))

  while true:
    while peek().kind == tkNewline: inc cursor
    if peek().kind == tkEof: break
    let r = parseNodeWith(source, visitor, stream, cursor)
    if r.isErr: return r

  ok(void, ParseError)

proc parseNodeWith[V](source: string, visitor: var V,
                      stream: TokenStream, cursor: var int):
    Result[void, ParseError] =
  ## Parse one node + its entries + (recursively) its children.
  ## Caller has positioned `cursor` at the node's first token (after any
  ## skipped leading newlines).
  mixin visitorCaps
  const caps = visitorCaps(V)

  template peek(off = 0): Token =
    if cursor + off < stream.tokens.len: stream.tokens[cursor + off]
    else: Token(kind: tkEof, span: pointSpan(StartPosition))

  # Skip an optional `(IDENT)` type annotation. KDL v2 allows them
  # before node names AND before any value (arg or prop).
  # 9'.1 scope: still skipped, not routed. 9'.2 wires the cap gate.
  template skipTypeAnno() =
    if peek().kind == tkLParen:
      inc cursor
      if peek().kind notin {tkIdent, tkString, tkRawString}:
        return err[void, ParseError](initError(peParseExpected, peek().span,
          "expected identifier or string inside type annotation"))
      inc cursor
      if peek().kind != tkRParen:
        return err[void, ParseError](initError(peParseExpected, peek().span,
          "expected ')' to close type annotation"))
      inc cursor

  skipTypeAnno()       # optional (type) before node name

  let nameTok = peek()
  if nameTok.kind != tkIdent:
    return err[void, ParseError](initError(peParseExpected, nameTok.span,
      "expected node name"))
  inc cursor

  # Read name bytes directly from source — skips interner.lookup
  # roundtrip. Safe because tkIdent is always a bare ident.
  let nameStart = nameTok.span.start.offset
  let nameLast = nameTok.span.finish.offset - 1
  let bRes = visitor.visitBeginNode(source.toOpenArray(nameStart, nameLast),
                                     nameTok.span)
  if bRes.isErr: return bRes

  var argIdx = 0
  while true:
    if peek().kind == tkLParen: skipTypeAnno()  # (type) prefix on arg value
    let t = peek()
    case t.kind
    of tkNewline, tkSemicolon, tkEof, tkRBrace:
      break
    of tkLBrace:
      # children block. Bracket inner-node walk with begin/end.
      # vcChildren-gated: visitors without children can skip the block
      # entirely (e.g. an enum-arg-only visitor).
      inc cursor   # consume `{`
      when vcChildren in caps:
        let bcRes = visitor.visitBeginChildren()
        if bcRes.isErr: return bcRes
      while true:
        while peek().kind == tkNewline: inc cursor
        if peek().kind == tkRBrace: break
        if peek().kind == tkEof:
          return err[void, ParseError](initError(peParseExpected, peek().span,
            "expected `}` to close children block"))
        when vcChildren in caps:
          let cRes = parseNodeWith(source, visitor, stream, cursor)
          if cRes.isErr: return cRes
        else:
          # Skip child node without emitting visitor events. Walk tokens
          # until matching `}` at this depth.
          var depth = 1
          while depth > 0 and peek().kind != tkEof:
            case peek().kind
            of tkLBrace: inc depth
            of tkRBrace: dec depth
            else: discard
            if depth > 0: inc cursor
          if peek().kind == tkRBrace: break
      inc cursor  # consume `}`
      when vcChildren in caps:
        let ecRes = visitor.visitEndChildren()
        if ecRes.isErr: return ecRes
      break    # children always terminate the node body in this slice
    of tkIdent, tkString, tkRawString:
      if peek(1).kind == tkEquals:
        let keyTok = peek()
        cursor += 2
        skipTypeAnno()       # optional (type) before prop value
        let valueTok = peek()
        inc cursor
        when vcProps in caps:
          if keyTok.kind == tkIdent:
            let ks = keyTok.span.start.offset
            let kl = keyTok.span.finish.offset - 1
            let pRes = visitor.visitProp(
                          source.toOpenArray(ks, kl), valueTok, stream)
            if pRes.isErr: return pRes
          else:
            let payload =
              if keyTok.kind == tkString:
                stream.stringPayloads[keyTok.strIdx]
              else:
                stream.rawStringPayloads[keyTok.rawIdx]
            let pRes = visitor.visitProp(
                          payload.toOpenArray(0, payload.high),
                          valueTok, stream)
            if pRes.isErr: return pRes
      else:
        inc cursor
        when vcArgs in caps:
          let aRes = visitor.visitArg(argIdx, t, stream)
          if aRes.isErr: return aRes
          inc argIdx
    of tkNumber, tkKeyword:
      inc cursor
      when vcArgs in caps:
        let aRes = visitor.visitArg(argIdx, t, stream)
        if aRes.isErr: return aRes
        inc argIdx
    else:
      return err[void, ParseError](initError(peParseUnexpected, t.span,
        "unexpected token in node entries"))

  let eRes = visitor.visitEndNode()
  if eRes.isErr: return eRes
  ok(void, ParseError)

proc parseWith*[V](source: string, visitor: var V,
                   sourcePath = "<input>"): Result[void, ParseError] =
  ## Single-node convenience. Delegates to parseDocumentWith so the
  ## LBrace/children/recovery logic lives in one place.
  parseDocumentWith(source, visitor, sourcePath)
