## Visitor-based typed parser. The first part of the typed-direct path
## architecture from issue #1.
##
## ## Design (per "E′" recommendation, see issue #1 discussion)
##
## One grammar, many visitors. The parser walks the token stream and
## dispatches into the visitor's methods. Visitors that live in tree:
##   - `DocBuilder` (src/doc_builder.nim) builds the existing `KdlDoc`
##   - `TypedBuilder[T]` (generated by `deriveVisitor`) writes directly
##     into a typed T value
##
## Visitors are duck-typed: any object with the required methods
## satisfies the protocol. The compiler monomorphizes per-visitor so
## the dispatch is static and inline-able.
##
## ## Capability-driven specialization
##
## Each visitor declares a `visitorCaps` template returning a compile-
## time `set[VisitorCap]`. parseDocumentWith branches on `when X in
## visitorCaps(V):` so visitors that don't need a feature don't pay for
## the routing code. Zero abstraction tax: TypedBuilder's hot path
## stays identical to before this refactor.
##
## ## Visitor protocol (core methods, required for all visitors)
##
##   proc visitBeginNode(v: var V, nameStr: openArray[char], nodeSpan: Span):
##       Result[void, ParseError]
##   proc visitArg(v: var V, idx: int, tok: Token, stream: TokenStream):
##       Result[void, ParseError]
##   proc visitProp(v: var V, keyStr: openArray[char],
##                  tok: Token, stream: TokenStream):
##       Result[void, ParseError]
##   proc visitBeginChildren(v: var V): Result[void, ParseError]
##   proc visitEndChildren(v: var V): Result[void, ParseError]
##   proc visitEndNode(v: var V): Result[void, ParseError]
##
## Optional methods (only required if the corresponding cap is declared):
##   visitNodeTypeAnno, visitValueTypeAnno   (vcNodeAnno / vcValueAnno)
##   visitSlashdash                          (vcSlashdash)
##
## All methods return `Result[void, ParseError]` so errors propagate
## without raising (preserves `embed[T]` compile-time-eval semantics).

import ./[lexer, intern, spans]

type
  VisitorCap* = enum
    ## Capabilities a visitor opts into. parseDocumentWith gates routing
    ## code per cap so unused features cost nothing.
    vcArgs            ## visitArg events for positional values
    vcProps           ## visitProp events for `key=value`
    vcChildren        ## visitBeginChildren / visitEndChildren + recursion
    vcNodeAnno        ## visitNodeTypeAnno before visitBeginNode
    vcValueAnno       ## visitValueTypeAnno before visitArg / visitProp
    vcSlashdash       ## visitSlashdash before slashdash'd thing

func openArrayToString*(s: openArray[char]): string {.noSideEffect.} =
  ## VM-friendly conversion. `cast[string](@seq[char])` blows up in
  ## NimVM ("does not support 'cast' from tySequence to tyString"); a
  ## newString + byte-copy works both at runtime and at compile time.
  ## Used in error messages only — the hot-path dispatch uses bytesEq.
  result = newString(s.len)
  for i in 0 ..< s.len: result[i] = s[i]

func bytesEq*(s: openArray[char], lit: static string): bool
    {.inline, noSideEffect.} =
  ## Zero-alloc byte compare against a compile-time-known string.
  if s.len != lit.len: return false
  for i in 0 ..< lit.len:
    if s[i] != lit[i]: return false
  true

proc parseInto*[T](source: string, sourcePath = "<input>"):
    Result[T, ParseError] =
  ## Typed entry point. Resolves the per-type visitor via
  ## `deriveVisitor`-emitted `kdlBuildVisitor` / `kdlBuildVisitorSeq`
  ## overload at instantiation time.
  mixin kdlBuildVisitor, kdlBuildVisitorSeq
  when T is seq:
    type Elem = typeof(default(T)[0])
    kdlBuildVisitorSeq(Elem, source, sourcePath)
  else:
    kdlBuildVisitor(T, source, sourcePath)

# ---------------------------------------------------------------------------
# parseDocumentWith — visitor-parameterized parser
# ---------------------------------------------------------------------------

proc parseNodeWith[V](source: string, visitor: var V,
                      stream: TokenStream, cursor: var int,
                      skip: bool = false):
    Result[void, ParseError]

proc parseDocumentWith*[V](source: string, visitor: var V,
                           sourcePath = "<input>"):
    Result[void, ParseError] =
  ## Walks every top-level node in `source` through `visitor`.
  ## A leading `/-` slashdash-marks the next node as discarded — its
  ## tokens are still parsed (so syntax errors inside it surface), but
  ## no visitor events fire for it.
  mixin visitorCaps
  var interner = initInterner()
  interner.disabled = true   # visitors read bytes from source directly
  let stream = lex(source, interner)
  for t in stream.tokens:
    if t.kind == tkError:
      return err[void, ParseError](stream.errorPayloads[t.errIdx])

  var cursor = 0
  template peek(off = 0): Token =
    if cursor + off < stream.tokens.len: stream.tokens[cursor + off]
    else: Token(kind: tkEof, span: pointSpan(StartPosition))

  while true:
    while peek().kind == tkNewline: inc cursor
    var skipNode = false
    if peek().kind == tkSlashDash:
      inc cursor
      while peek().kind == tkNewline: inc cursor  # /- crosses newlines
      skipNode = true
    if peek().kind == tkEof: break
    let r = parseNodeWith(source, visitor, stream, cursor, skip = skipNode)
    if r.isErr: return r

  ok(void, ParseError)

proc parseNodeWith[V](source: string, visitor: var V,
                      stream: TokenStream, cursor: var int,
                      skip: bool = false):
    Result[void, ParseError] =
  ## Parse one node + its entries + (recursively) its children.
  ## When `skip` is true, tokens are still parsed (preserving syntax-
  ## error surfaces) but no visitor events fire — used by slashdash.
  mixin visitorCaps
  const caps = visitorCaps(V)

  template peek(off = 0): Token =
    if cursor + off < stream.tokens.len: stream.tokens[cursor + off]
    else: Token(kind: tkEof, span: pointSpan(StartPosition))

  # Optional `(IDENT|STRING|RAW_STRING)` type annotation. Caps decide
  # whether the event can fire at all (compile-time); `noEmit` lets the
  # caller suppress emission per-call (runtime, used for slashdash'd
  # entries within an otherwise emitting parse).
  template handleTypeAnno(canEmit: static bool, emitProc: untyped,
                          noEmit: bool) =
    if peek().kind == tkLParen:
      let lParenSpan = peek().span
      inc cursor
      let annoTok = peek()
      if annoTok.kind notin {tkIdent, tkString, tkRawString}:
        return err[void, ParseError](initError(peParseExpected, annoTok.span,
          "expected identifier or string inside type annotation"))
      inc cursor
      if peek().kind != tkRParen:
        return err[void, ParseError](initError(peParseExpected, peek().span,
          "expected ')' to close type annotation"))
      let rParenSpan = peek().span
      inc cursor
      when canEmit:
        if not noEmit:
          let annoSpan = initSpan(lParenSpan.start, rParenSpan.finish)
          case annoTok.kind
          of tkIdent:
            let s = annoTok.span.start.offset
            let l = annoTok.span.finish.offset - 1
            let r = visitor.emitProc(source.toOpenArray(s, l), annoSpan)
            if r.isErr: return r
          of tkString:
            let p = stream.stringPayloads[annoTok.strIdx]
            let r = visitor.emitProc(p.toOpenArray(0, p.high), annoSpan)
            if r.isErr: return r
          of tkRawString:
            let p = stream.rawStringPayloads[annoTok.rawIdx]
            let r = visitor.emitProc(p.toOpenArray(0, p.high), annoSpan)
            if r.isErr: return r
          else: discard  # unreachable

  template handleNodeAnno(noEmit: bool) =
    when vcNodeAnno in caps:
      handleTypeAnno(true, visitNodeTypeAnno, noEmit)
    else:
      handleTypeAnno(false, visitNodeTypeAnno, noEmit)

  template handleValueAnno(noEmit: bool) =
    when vcValueAnno in caps:
      handleTypeAnno(true, visitValueTypeAnno, noEmit)
    else:
      handleTypeAnno(false, visitValueTypeAnno, noEmit)

  handleNodeAnno(skip)   # optional (type) before node name

  let nameTok = peek()
  if nameTok.kind notin {tkIdent, tkString, tkRawString}:
    return err[void, ParseError](initError(peParseExpected, nameTok.span,
      "expected node name"))
  inc cursor

  # Bare ident → read from source (skips interner roundtrip).
  # Quoted/raw → use the lexer's payload table (escapes already
  # resolved). The visitor sees the SAME unescaped bytes either way.
  # Validate node-name shape (reject reserved barewords + bidi controls)
  # whether or not we'll emit — KDL v2 forbids these regardless.
  case nameTok.kind
  of tkIdent:
    let s = nameTok.span.start.offset
    let l = nameTok.span.finish.offset - 1
    if isReservedBareword(source.toOpenArray(s, l)):
      let name = source[s .. l]
      return err[void, ParseError](initError(peLexReservedKeyword, nameTok.span,
        "reserved keyword '" & name &
        "' cannot be used as a bare node name; quote it or use '#" &
        name & "'"))
    if not skip:
      let bRes = visitor.visitBeginNode(source.toOpenArray(s, l), nameTok.span)
      if bRes.isErr: return bRes
  of tkString:
    let p = stream.stringPayloads[nameTok.strIdx]
    if containsBidiControl(p):
      return err[void, ParseError](initError(peLexInvalidIdentifier, nameTok.span,
        "bidi control codepoint in node name"))
    if not skip:
      let bRes = visitor.visitBeginNode(p.toOpenArray(0, p.high), nameTok.span)
      if bRes.isErr: return bRes
  of tkRawString:
    let p = stream.rawStringPayloads[nameTok.rawIdx]
    if containsBidiControl(p):
      return err[void, ParseError](initError(peLexInvalidIdentifier, nameTok.span,
        "bidi control codepoint in node name"))
    if not skip:
      let bRes = visitor.visitBeginNode(p.toOpenArray(0, p.high), nameTok.span)
      if bRes.isErr: return bRes
  else: discard   # unreachable

  var argIdx = 0
  # KDL v2 spec: once any children block (real or slashdash'd) has been
  # consumed, no more entries may appear. At most one REAL block may
  # contribute children; slashdash'd ones may freely interleave.
  var seenChildrenBlock = false
  var realChildrenSeen = false
  while true:
    # Entry-level slashdash: skips the next single entry OR children block.
    # Chained `/- /-` isn't valid grammar (the second /- has no entry to
    # skip), so single-`if` lookahead suffices and stays branch-predictable.
    var entrySkip = skip
    var sawSlashdash = false
    if peek().kind == tkSlashDash:
      inc cursor
      while peek().kind == tkNewline: inc cursor
      entrySkip = true
      sawSlashdash = true

    # Snapshot entry-start precededByWs BEFORE annotation consumption —
    # `(type)value` is one entry; the precededByWs property belongs to
    # the leading `(`. Doing the check after handleValueAnno would test
    # the value token, which never has ws after the closing `)`.
    let entryStartTok = peek()
    if not sawSlashdash and not entryStartTok.precededByWs and
       entryStartTok.kind notin {tkNewline, tkSemicolon, tkEof, tkRBrace}:
      return err[void, ParseError](initError(peParseExpected, entryStartTok.span,
        "whitespace required before this entry"))

    if peek().kind == tkLParen: handleValueAnno(entrySkip)
    let t = peek()
    case t.kind
    of tkNewline, tkSemicolon, tkEof, tkRBrace:
      break
    else: discard

    # Entries-after-children check. Any entry token (not LBrace) reaching
    # here AFTER seenChildrenBlock is a violation.
    if seenChildrenBlock and t.kind != tkLBrace:
      return err[void, ParseError](initError(peParseUnexpected, t.span,
        "entries are not permitted after a children block"))

    # Entries-after-children check. Any entry token (not LBrace) reaching
    # here AFTER seenChildrenBlock is a violation.
    if seenChildrenBlock and t.kind != tkLBrace:
      return err[void, ParseError](initError(peParseUnexpected, t.span,
        "entries are not permitted after a children block"))

    case t.kind
    of tkNewline, tkSemicolon, tkEof, tkRBrace:
      break    # unreachable (handled above), satisfies exhaustiveness
    of tkLBrace:
      # Children block. Inner nodes recurse through parseNodeWith with
      # skip = entrySkip; visitor children-boundary events fire iff
      # vcChildren is declared AND the enclosing node isn't skipped.
      if not entrySkip and realChildrenSeen:
        return err[void, ParseError](initError(peParseUnexpected, t.span,
          "a node may have at most one real children block"))
      inc cursor   # consume `{`
      seenChildrenBlock = true
      if not entrySkip:
        realChildrenSeen = true
      when vcChildren in caps:
        if not entrySkip:
          let bcRes = visitor.visitBeginChildren()
          if bcRes.isErr: return bcRes
      while true:
        while peek().kind == tkNewline: inc cursor
        if peek().kind == tkRBrace: break
        if peek().kind == tkEof:
          return err[void, ParseError](initError(peParseExpected, peek().span,
            "expected `}` to close children block"))
        # Inner-node slashdash within children
        var innerSkip = entrySkip
        if peek().kind == tkSlashDash:
          inc cursor
          while peek().kind == tkNewline: inc cursor
          innerSkip = true
        when vcChildren in caps:
          let cRes = parseNodeWith(source, visitor, stream, cursor,
                                   skip = innerSkip)
          if cRes.isErr: return cRes
        else:
          # Cap absent — walk and discard without recursion.
          var depth = 1
          while depth > 0 and peek().kind != tkEof:
            case peek().kind
            of tkLBrace: inc depth
            of tkRBrace: dec depth
            else: discard
            if depth > 0: inc cursor
          if peek().kind == tkRBrace: break
      inc cursor  # consume `}`
      when vcChildren in caps:
        if not entrySkip:
          let ecRes = visitor.visitEndChildren()
          if ecRes.isErr: return ecRes
      # KDL v2 grammar allows multiple slashdash'd children blocks +
      # at most one real one (validated by parser.nim, not here yet —
      # slice 9'.7). Loop to continue eating remaining /-{} blocks.
      continue
    of tkIdent, tkString, tkRawString:
      if peek(1).kind == tkEquals:
        let keyTok = peek()
        cursor += 2
        handleValueAnno(entrySkip)
        let valueTok = peek()
        inc cursor
        # Validate key shape unconditionally — bare reserved keywords +
        # bidi-tainted quoted/raw keys are grammar-level errors that
        # apply to every visitor, even those without vcProps.
        case keyTok.kind
        of tkIdent:
          let ks = keyTok.span.start.offset
          let kl = keyTok.span.finish.offset - 1
          if isReservedBareword(source.toOpenArray(ks, kl)):
            return err[void, ParseError](initError(peLexReservedKeyword,
              keyTok.span,
              "reserved keyword '" & source[ks .. kl] &
              "' cannot be used as a property key"))
          when vcProps in caps:
            if not entrySkip:
              let pRes = visitor.visitProp(source.toOpenArray(ks, kl),
                                          valueTok, stream)
              if pRes.isErr: return pRes
        of tkString:
          let p = stream.stringPayloads[keyTok.strIdx]
          if containsBidiControl(p):
            return err[void, ParseError](initError(peLexInvalidIdentifier,
              keyTok.span, "bidi control codepoint in property key"))
          when vcProps in caps:
            if not entrySkip:
              let pRes = visitor.visitProp(p.toOpenArray(0, p.high),
                                          valueTok, stream)
              if pRes.isErr: return pRes
        of tkRawString:
          let p = stream.rawStringPayloads[keyTok.rawIdx]
          if containsBidiControl(p):
            return err[void, ParseError](initError(peLexInvalidIdentifier,
              keyTok.span, "bidi control codepoint in property key"))
          when vcProps in caps:
            if not entrySkip:
              let pRes = visitor.visitProp(p.toOpenArray(0, p.high),
                                          valueTok, stream)
              if pRes.isErr: return pRes
        else: discard   # unreachable
      else:
        # Arg value. tkIdent as arg is a bare-id string per KDL v2,
        # but must not be a reserved keyword.
        if t.kind == tkIdent:
          let s = t.span.start.offset
          let l = t.span.finish.offset - 1
          if isReservedBareword(source.toOpenArray(s, l)):
            let name = source[s .. l]
            return err[void, ParseError](initError(peLexReservedKeyword,
              t.span,
              "reserved keyword '" & name &
              "' cannot be used as a bare value; quote it or use '#" &
              name & "'"))
        elif t.kind == tkString:
          let p = stream.stringPayloads[t.strIdx]
          if containsBidiControl(p):
            return err[void, ParseError](initError(peLexInvalidIdentifier,
              t.span, "bidi control codepoint in string value"))
        elif t.kind == tkRawString:
          let p = stream.rawStringPayloads[t.rawIdx]
          if containsBidiControl(p):
            return err[void, ParseError](initError(peLexInvalidIdentifier,
              t.span, "bidi control codepoint in string value"))
        inc cursor
        when vcArgs in caps:
          if not entrySkip:
            let aRes = visitor.visitArg(argIdx, t, stream)
            if aRes.isErr: return aRes
            inc argIdx
    of tkNumber, tkKeyword:
      inc cursor
      when vcArgs in caps:
        if not entrySkip:
          let aRes = visitor.visitArg(argIdx, t, stream)
          if aRes.isErr: return aRes
          inc argIdx
    else:
      return err[void, ParseError](initError(peParseUnexpected, t.span,
        "unexpected token in node entries"))

  if not skip:
    let eRes = visitor.visitEndNode()
    if eRes.isErr: return eRes
  ok(void, ParseError)

proc parseWith*[V](source: string, visitor: var V,
                   sourcePath = "<input>"): Result[void, ParseError] =
  ## Single-node convenience. Delegates to parseDocumentWith so the
  ## LBrace/children/recovery logic lives in one place.
  parseDocumentWith(source, visitor, sourcePath)
